import "./ui/globals.css";

export const metadata = {
  title: "Next.js 14 Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-darkHard text-white">
        {children}
      </body>
    </html>
  );
}
